{"frames":[{"func":"test_that(\"number input fails\", expect_error(f(1)))","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"test_code(desc, code, env = parent.frame())","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"get_reporter()$end_test(context = get_reporter()$.context, test = test)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"stop(message, call. = FALSE)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0}],"message":"Error: Test failed: 'number input fails'\n* `f(1)` did not throw an error.\n"}